# Configuration for librarian-puppet. For example:
#
# forge "http://forge.puppetlabs.com"
#
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
#
# mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
#
# mod "stdlib",
#   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "puppetlabs/apt"
mod "puppetlabs/concat"
mod "puppetlabs/postgresql"
mod "puppetlabs/passenger"
mod "johanek/redmine"